### ISSUE TITLE
Feature Request: Enable Music Playback on Music Card Click

### ISSUE THREAD

**Issue by KhairulIslamAK** [Ryneex/Musify#5]
Currently, in the home page, users need to click the play button on the music card to start playback. However, it would be more user-friendly if users could simply click anywhere on the music card to start playing the music. This would streamline the playback experience and improve usability.

**Comment by ryneex** [comment]
Thanks for the suggestion! I'll start working on it since it won't take long. I'll give you an update once it's finished.

**Comment by ryneex** [comment]
@KhairulIslamAK The feature is now live in the app

**Comment by KhairulIslamAK** [comment]
Thank You 🥰
