### ISSUE TITLE
 Feature Request: Add Sound Wave When Music is Playing (Like Spotify)

### ISSUE THREAD

**Issue by KhairulIslamAK** [Ryneex/Musify#7]
![Screenshot 2024-05-11 030835](https://github.com/Ryneex/Musify/assets/165030968/d5dc354a-8b81-4691-8cc0-ebca6ac577b0)

I would like to suggest the implementation of a visual representation of sound waves when music is playing, similar to what is seen in Spotify. This feature would enhance the user experience by providing a dynamic and engaging visualization of the audio being played.

**Comment by ryneex** [comment]
Thanks for the suggestion, I will include it.

**Comment by ryneex** [comment]
@KhairulIslamAK Your feature request is now live. Thanks for helping me improve Musify
